#from main import getPipelineFolder
from ..default_values import GITHUB_FOLDER
from .muse import *
from .mutect import *
from .somaticsniper import *
from .strelka import * 
from .varscan import *
from .freec import *
from .cnvkit import *