#from main import getPipelineFolder
from .basequalityscorerecalibration import *
from .haplotypecaller import *
from .muse import *
from .mutect import *
from .somaticsniper import *
from .strelka import * 
from .varscan import *
from .freec import *
from .cnvkit import *